sudo: required
services:
  - docker

before_install:
  - docker build -t pervezalam777/dynamic-react-form -f Dockerfile.dev .

script:
  - docker run -e CI=true pervezalam777/dynamic-react-form npm run test -- --coverage --watchAll=false